apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service # Add a unique name for the component
  annotations:
    gitlab.com/project-id: '60030582' #1234. This must be in quotes and can be found under Settings --> General
    # or
    gitlab.com/project-slug: 'project-slug' # group_name/project_name
    # or
    gitlab.com/instance: gitlab.internal.abcd # abcd, represents local instance used
spec:
  type: service
  lifecycle: production # Add a lifecycle field with a valid value such as 'development', 'production', or 'decommissioned'
  # Add additional spec fields as required
